### ISSUE TITLE
Node: Subtract is being weird?

### ISSUE THREAD

**Issue by enlore** [code-for-nashville/oss-intro-class#16]
Not sure what to make of this. Subtraction is something my feeble human brain can do without a computer, so I was surprised when the computer program kept getting it wrong.

```
Node v6.9.1
Type .help for more information
nesh> const am = require('./index.js')
undefined
nesh> am.subtract(3, 1)
3
nesh> am.subtract(7, 4)
7
nesh>
```

**Comment by abarnhard** [comment]
I'd like to tackle this issue

**Comment by danwventura** [comment]
Same

**Comment by scarnz** [comment]
I think I've located the cause of the problem
